[package]
name = "alpacker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
zstd = { workspace = true }
twox-hash = { workspace = true }
lazy_static = "1.5.0"

[features]
default = ["collect-errors"]
collect-errors = []
