[package]
name = "alpacker-packer"
version = "0.1.0"
edition = "2024"

[dependencies]
alpacker = { workspace = true }

serde = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
zstd = { workspace = true }
twox-hash = { workspace = true }
const_format = { version = "0.2.34", features = ["rust_1_83"] }
oxipng = "9.1.4"
glob = "0.3.2"

[dev-dependencies]
testdir = { workspace = true }
