# ChatGPT wrote this :D
name: Rust CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Cargo Tests and Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check with all features
        run: cargo check --all-features

      - name: Check with no default features
        run: cargo check --no-default-features

      - name: Run tests
        run: cargo test --all
